# Generated by Django 5.2.13 on 2026-05-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('usado', 'Usado'), ('reparado', 'Reparado'), ('reacondicionado', 'Reacondicionado'), ('nuevo', 'Nuevo')], default='usado', max_length=20),
        ),
    ]
